### ISSUE TITLE
Remove Netlify integration

### ISSUE THREAD

**Issue by karenmajewicz** [geo4lib/geo4libcamp-website#13]
This repository is currently configured with Netlify and I believe that the geo4libcamp.org domain is also pointing to Netlify. This site will be easier to maintain over the long term if the integration is removed. 

For example, Netlify had stopped running due to a  permissions update that had to be manually accepted. However, troubleshooting took quite awhile as I only discovered this after exploring the Integration tab in Settings.  Also, Netlify is expecting a certain type of Jekyll site, but I have simplified this repo to use straight HTML. Therefore, the tests are not passing.

I believe that I can get the site to update again by re-installing Jekyll. However, the complexity required to run things through Netlify does not seem to be needed at this point.

**Comment by karenmajewicz** [comment]
@kimdurante

**Comment by thatbudakguy** [comment]
netlify has been removed.
